
// El string que contiene la información de los cursos
const cursosString = `1101	CALCULO DIFERENCIAL	4	OBLIGATORIO
1102	MATEMATICA BASICA	4	OBLIGATORIO
1103	LENGUA Y COMPRENSION DE LECTURA	2	OBLIGATORIO
1104	FUNDAMENTOS DE PROGRAMACION Y COMPUTACION	4	OBLIGATORIO
1105	QUIMICA GENERAL	4	OBLIGATORIO
1106	REINGENIERIA MENTAL	3	OBLIGATORIO
1201	FISICA I	4	OBLIGATORIO
1202	CALCULO INTEGRAL	4	OBLIGATORIO
1203	FILOSOFIA DE SISTEMAS	3	OBLIGATORIO
1204	PROGRAMACION I	4	OBLIGATORIO
1205	MATEMATICA DISCRETA	4	OBLIGATORIO
1206	LENGUA ESPAÑOLA	3	ELECTIVO
1207	HERRAMIENTAS GRAFICAS PARA INGENIERIA	3	ELECTIVO
2101	FISICA II	4	OBLIGATORIO
2102	ECUACIONES DIFERENCIALES	4	OBLIGATORIO
2103	PROGRAMACION II	3	OBLIGATORIO
2104	SISTEMAS ECONOMICOS	3	OBLIGATORIO
2105	TEORIA GENERAL Y CIENCIA DE SISTEMAS	3	OBLIGATORIO
2106	PROBABILIDADES Y ESTADISTICA	4	OBLIGATORIO
2107	INTRODUCCION A LA COMPUTACION	3	ELECTIVO
2108	TEORIA DE LENGUAJES Y COMPILADORES	3	ELECTIVO
2109	INGENIERIA DE REQUERIMIENTOS	3	ELECTIVO
2201	FISICA MODERNA	3	OBLIGATORIO
2202	METODOS ESTADISTICOS	4	OBLIGATORIO
2203	TEORIA Y DISEÑO DE BASES DE DATOS	4	OBLIGATORIO
2204	CIBERNETICA Y TEORIA DE CONTROL	4	OBLIGATORIO
2205	METODOLOGIA DE LOS SISTEMAS BLANDOS	3	OBLIGATORIO
2206	CONTABILIDAD, COSTOS Y FINANZAS	3	OBLIGATORIO
2207	ELECTRONICA DIGITAL	3	ELECTIVO
3101	TALLER DE INVESTIGACION CIENTIFICA	3	OBLIGATORIO
3102	INVESTIGACION DE OPERACIONES I	4	OBLIGATORIO
3103	DINAMICA DE SISTEMAS	4	OBLIGATORIO
3104	ANALISIS Y DISEÑO DE SISTEMAS DE INFORMACION	4	OBLIGATORIO
3105	METODOS NUMERICOS	3	OBLIGATORIO
3106	TEORIA Y DISEÑO ORGANIZACIONAL	3	OBLIGATORIO
3201	TALLER DE METODOLOGIA DE LOS SISTEMAS BLANDOS	2	OBLIGATORIO
3202	PSICOLOGIA SISTEMICA	3	OBLIGATORIO
3203	SISTEMAS OPERATIVOS	3	OBLIGATORIO
3204	INVESTIGACIÓN DE OPERACIONES II	4	OBLIGATORIO
3205	DISEÑO Y GESTION DE PROCESOS	4	OBLIGATORIO
3206	SISTEMAS BIOLOGICOS	3	OBLIGATORIO
3207	ALGORITMO Y ESTRUCTURA DE DATOS	3	ELECTIVO
3208	FUNDAMENTOS DE COMUNICACION Y TELECOMUNICACIONES	3	ELECTIVO
4101	TALLER DE DINAMICA DE SISTEMAS	2	OBLIGATORIO
4102	SISTEMAS SOCIO POLITICOS	3	OBLIGATORIO
4103	INGENIERIA DE SOFTWARE I	3	OBLIGATORIO
4104	SIMULACION	3	OBLIGATORIO
4105	ARQUITECTURA DE LAS TECNOLOGIAS DE INFORMACION Y COMUNICACION	4	OBLIGATORIO
4106	MICROPROCESADORES	3	ELECTIVO
4107	COMPORTAMIENTO ORGANIZACIONAL	3	ELECTIVO
4108	ADMINISTRACION DE BASE DE DATOS	3	ELECTIVO
4201	ESTUDIO DE LA REALIDAD NACIONAL Y REGIONAL	3	OBLIGATORIO
4202	MODELO DE LOS SISTEMAS VIABLES	4	OBLIGATORIO
4203	PROSPECTIVA	3	OBLIGATORIO
4204	SEGURIDAD Y AUDITORIA INFORMATICA	4	OBLIGATORIO
4205	PLANEAMIENTO ESTRATEGICO Y CUADRO DE MANDO	3	OBLIGATORIO
4206	SISTEMAS EXPERTOS	3	ELECTIVO
4207	NEGOCIOS Y GOBIERNO ELECTRONICO	3	ELECTIVO
4208	SISTEMAS INTEGRADOS	3	ELECTIVO
5101	SISTEMAS COMPLEJOS	4	OBLIGATORIO
5102	INTELIGENCIA DE NEGOCIOS	3	OBLIGATORIO
5103	RESPONSABILIDAD SOCIAL Y DEFENSA NACIONAL	2	OBLIGATORIO
5104	PROYECTO INTER Y TRANSDISCIPLINARIO I	4	OBLIGATORIO
5105	GESTION DE PROYECTOS	4	OBLIGATORIO
5106	GESTION DEL CONOCIMIENTO	3	ELECTIVO
5107	INTELIGENCIA ARTIFICIAL	3	ELECTIVO
5108	SISTEMAS ORGANIZACIONALES MODERNOS	3	ELECTIVO
5109	REDES Y CONECTIVIDAD	3	ELECTIVO
5201	INGENIERIA EMPRESARIAL	4	OBLIGATORIO
5202	PROYECTO INTER Y TRANSDISCIPLINARIO II	4	OBLIGATORIO
5203	INGENIERIA DE SOFTWARE II	3	ELECTIVO
5204	TENDENCIAS TECNOLOGICAS Y APLICACIONES SISTEMICAS	3	ELECTIVO
5205	REALIDAD VIRTUAL	3	ELECTIVO
5206	MARKETING Y JUEGO DE NEGOCIOS	3	ELECTIVO`

// Array para almacenar los objetos de cursos
const cursosArray = []

// Dividir el string por saltos de línea y luego por espacios
const lineas = cursosString.split('\n')
lineas.forEach(linea => {
  // split replace for tab
  const datos = linea.split('\t')

  const curso = {
    id: datos[0],
    data: {
      label: datos[1],
      creditos: parseInt(datos[datos.length - 2]),
      tipoCurso: datos[datos.length - 1],
      finished: false
    },
    position: {
      x: 0,
      y: 0
    },
    targetPosition: "left",
    sourcePosition: "right",
    type: "colorChooser"
  }
  cursosArray.push(curso)
})

// agregar main al inicio
cursosArray.unshift({
  id: "main",
  data: {
    label: "INGENIERÍA DE SISTEMAS", // cambiar por el nombre de la carrera
    color: "#0041d0"
  },
  "position": {
    x: 0,
    y: 0
  },
  targetPosition: "left",
  sourcePosition: "right",
  type: "colorChooser"
})

const nodes = cursosArray as Node[]

export default nodes
